//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, PartialOrd, Ord,
)]
#[sea_orm(table_name = "schedule_game")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub schedule_id: i32,
    pub start: Option<String>,
    pub end: Option<String>,
    pub schedule_game_group: Option<i32>,
    pub team_one: Option<i32>,
    pub team_two: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::schedule::Entity",
        from = "Column::ScheduleId",
        to = "super::schedule::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Schedule,
    #[sea_orm(
        belongs_to = "super::schedule_game_group::Entity",
        from = "Column::ScheduleGameGroup",
        to = "super::schedule_game_group::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ScheduleGameGroup,
    #[sea_orm(
        belongs_to = "super::schedule_team::Entity",
        from = "Column::TeamTwo",
        to = "super::schedule_team::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ScheduleTeam2,
    #[sea_orm(
        belongs_to = "super::schedule_team::Entity",
        from = "Column::TeamOne",
        to = "super::schedule_team::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ScheduleTeam1,
}

impl Related<super::schedule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Schedule.def()
    }
}

impl Related<super::schedule_game_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleGameGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
