//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, PartialOrd, Ord,
)]
#[sea_orm(table_name = "schedule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub created: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::schedule_game::Entity")]
    ScheduleGame,
    #[sea_orm(has_many = "super::schedule_game_group::Entity")]
    ScheduleGameGroup,
    #[sea_orm(has_many = "super::schedule_team::Entity")]
    ScheduleTeam,
}

impl Related<super::schedule_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleGame.def()
    }
}

impl Related<super::schedule_game_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleGameGroup.def()
    }
}

impl Related<super::schedule_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleTeam.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
