//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, PartialOrd, Ord,
)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub region_owner: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::region::Entity",
        from = "Column::RegionOwner",
        to = "super::region::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Region,
    #[sea_orm(has_many = "super::team_group_join::Entity")]
    TeamGroupJoin,
}

impl Related<super::region::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Region.def()
    }
}

impl Related<super::team_group_join::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamGroupJoin.def()
    }
}

impl Related<super::team_group::Entity> for Entity {
    fn to() -> RelationDef {
        super::team_group_join::Relation::TeamGroup.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::team_group_join::Relation::Team.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
