services:
  grpc_server:
    build:
      context: .\
      dockerfile: .\gcloud\grpc_server\Dockerfile
    ports:
      - 50051:50051
    expose:
      - 50051 
    env_file:
      - .\gcloud\grpc_server\.env